# Generated by Django 3.0 on 2019-12-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Squirreldata',
            fields=[
                ('longitude', models.CharField(help_text='longitude', max_length=17)),
                ('latitude', models.CharField(help_text='latitude', max_length=16)),
                ('unique_squirrel_id', models.CharField(help_text='unique tag for each squirrel', max_length=14, primary_key=True, serialize=False)),
                ('shift', models.CharField(blank=True, help_text='morning or late afternoon', max_length=2)),
                ('date', models.DateTimeField(help_text='Concatenation of the sighting session day and month', max_length=20)),
                ('age', models.CharField(blank=True, help_text="Squirrel's age", max_length=8)),
                ('fur_color', models.CharField(blank=True, help_text='Squirrel Primal Fur Color', max_length=8)),
                ('location', models.CharField(blank=True, help_text='Location', max_length=12)),
                ('specific_location', models.CharField(blank=True, help_text='Specific Location', max_length=102)),
                ('running', models.BooleanField(default=False, help_text='Running')),
                ('chasing', models.BooleanField(default=False, help_text='Chasing')),
                ('climbing', models.BooleanField(default=False, help_text='Climbing')),
                ('eating', models.BooleanField(default=False, help_text='Eating')),
                ('foraging', models.BooleanField(default=False, help_text='Foraging')),
                ('other_activities', models.CharField(blank=True, help_text='Other Activities', max_length=140)),
                ('kuks', models.BooleanField(default=False, help_text='Kuks')),
                ('quaas', models.BooleanField(default=False, help_text='Quaas')),
                ('moans', models.BooleanField(default=False, help_text='Moans')),
                ('tail_flags', models.BooleanField(default=False, help_text='Tail flags')),
                ('tail_twitches', models.BooleanField(default=False, help_text='Tail twitches')),
                ('approaches', models.BooleanField(default=False, help_text='Approaches')),
                ('indifferent', models.BooleanField(default=False, help_text='Indifferent')),
                ('runs_from', models.BooleanField(default=False, help_text='Runs from')),
            ],
        ),
    ]
